version: 2.1
executors:
  build-executor:
    environment:
      IMAGE_NAME: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: andrewpgit/alpine-git:3.11
    working_directory: ~/build
jobs:
  build:
    executor: build-executor

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            echo "Install packages"
            VER='18.06.3-ce'
            apk add --no-cache libffi-dev openssl-dev gcc libc-dev make git
            wget -O /tmp/docker-${VER}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${VER}.tgz
            tar -xz -C /tmp -f /tmp/docker-${VER}.tgz
            mv /tmp/docker/* /usr/local/bin/

      - run:
          name: build images
          command: |
            echo ${CIRCLE_BRANCH}
            make  -e IMAGE_NAME=${IMAGE_NAME} -e TAG=latest build
      - run:
          name: Archive docker image.
          command: |
              make -e IMAGE_NAME=${IMAGE_NAME}  archive

      - persist_to_workspace:
        root: .
        paths:
          - ./image.tar


  


workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
