version: 2.1
executors:
  build-executor:
    environment:
      IMAGE_NAME: ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: alpine:3.10
jobs:
  build:
    executor: build-executor
    working_directory: ~/build

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            echo "Install packages"
            VER='18.06.3-ce'
            apk add libffi-dev openssl-dev gcc libc-dev make
            wget -O /tmp/docker-${VER}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${VER}.tgz
            tar -xz -C /tmp -f /tmp/docker-${VER}.tgz
            mv /tmp/docker/* /usr/local/bin/
      - setup_remote_docker

      - run:
          name: build images
          command: |
            echo ${CIRCLE_BRANCH}
            make  -e IMAGE_NAME=${IMAGE_NAME} -e TAG=latest build

      - deploy:
          name: deployment
          command: |
            echo $IMAGE_NAME
            IMAGE_NAME="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            echo $IMAGE_NAME
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

            if  [ -n  "$CIRCLE_BRANCH" ]; then
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:${CIRCLE_BRANCH}-latest
                make -e IMAGE_NAME=${IMAGE_NAME} -e TAG=${CIRCLE_BRANCH}-latest release
            fi

            if  [ -n "$CIRCLE_TAG" ]; then
                echo   ${CIRCLE_BRANCH}
                docker tag ${IMAGE_NAME}:latest  ${IMAGE_NAME}:${CIRCLE_TAG}
                make -e IMAGE_NAME=${IMAGE_NAME} -e TAG=${CIRCLE_TAG} release
            fi


workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context: docker-context
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - /^dev-*/
